name: update-tap

on:
  workflow_run:
    workflows: [release]
    types: [completed]

jobs:
  update-tap:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: mac-exporter
          formula-path: Formula/mac-exporter.rb
          homebrew-tap: rpoetrap/homebrew-tap
          tag-name: ${{ github.event.workflow_run.head_branch }}
          download-url: https://github.com/rpoetrap/mac-exporter/releases/download/${{ github.event.workflow_run.head_branch }}/mac-exporter_Darwin_arm64.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_PAT }}
